### ISSUE TITLE
Optimize Frigate Performance / Utility

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/pi-nvr#8]
Frigate is looking like the head-and-shoulders winner for running on a Pi (at least Pi 5), especially in tandem with Coral. Would love to see other 'neural' TPUs supported too (Hailo... maybe the one built into some Rockchip SoCs?).

But I'm seeing that it won't scale too drastically with H.265, H.264, 4K, multiple cameras... it starts eating CPU just transcoding stuff and translating it for internal processing (`ffmpeg` is eating up 150% CPU constantly while just processing one 4K stream at H.265).

I want to make sure the Pi 5's built-in hardware decoding support is used where possible, and also make sure the TPU and any other little performance optimization is used to its fullest extent. And also streamline the deployment a bit, especially since I'd like one configuration to run both my home setup and my office (with different types and numbers of cameras).

Also would like to make it so I could easily swap over to a standard Linux PC at some point or maybe even try running it with Docker on my Mac (is that doable?), all with the same Ansible playbook.

Follow-up to #4.

**Comment by geerlingguy** [comment]
Using the substream (640x480, H265) for detect, I'm able to view the lower-res in browser, while clips and recordings are still done at full 4K resolution:

```yaml
cameras:
  basement:
    ffmpeg:
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -tag:v hvc1 -bsf:v hevc_mp4toannexb -c:a aac
        rtmp: -c:v copy -c:a aac -f flv
      inputs:
        - path: "rtsp://jgeerling:{FRIGATE_RTSP_PASSWORD}@cam02.geerli.net:554/H264/ch1/sub/av_stream"
          roles:
            - detect
        - path: "rtsp://jgeerling:{FRIGATE_RTSP_PASSWORD}@cam02.geerli.net:554/H264/ch1/main/av_stream"
          roles:
            - record
```

The CPU usage is down to like 40% overall (much less than one full core), and FPS for ffmpeg/Capture are capped at 5. The recordings and clips are all at 15 fps.

So... don't use the 4K stream for `detect`, only for `record` :)
